### ISSUE TITLE
Doesn't seem to retain data

### ISSUE THREAD

**Issue by chris13524** [rgolubtsov/virtblkiosim#14]
If I try to make a filesystem on the block device (`mkfs.ext4 /dev/virtblkiosim`) and then mount it (`mount -t ext4 /dev/virtblkiosim /mnt`), it fails with this error: "mount: /mnt: wrong fs type, bad option, bad superblock on /dev/virtblkiosim, missing codepage or helper program, or other error."

Further investigation reveals that it doesn't seem to be retaining data at all or the data is outputted randomly. For example, running `head /dev/virtblkiosim | hexdump` outputs different data each time it is ran.

Am I misunderstanding the function of this block device?

**Comment by rgolubtsov** [comment]
**Hi Chris,**

It's because this is a virtual block device and it doesn't correspond to a physical one like HDD/SSD disk drive. So any data transmitted and wrote to it via the `ioctl()` system call are exist only in-memory and didn't written to anywhere else.

Initially this driver was intended to make a somewhat handy utility (or a part of it) to mesure the latency of read/write IO ops, of course when connected to a physical device. But later on I've decided to write a template (or something similar) in order to create a starting springboard for developing such drivers in the future in a row. &ndash; To play with possible approaches to manipulate with the data: in the current implementation by use of the `ioctl` syscall only.

Additionally, this whole project is intended to provide a solid basis for novices on how to make an LKM and attach it and utilize it using virtualization-like approach from the ground up. That is to create a clean VM with the networking, build the driver's module, and attach it to the kernel. Finally, to make some tests over it. That's it. :dvd:

**Comment by chris13524** [comment]
Hi @rgolubtsov and thanks for that information. Perhaps I misunderstood what this project was doing, but I switched to forking [BUSE](https://github.com/acozzette/BUSE) instead to make my custom block device.
